/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: cast_channel.proto */

#ifndef PROTOBUF_C_cast_5fchannel_2eproto__INCLUDED
#define PROTOBUF_C_cast_5fchannel_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Api__CastMessage Api__CastMessage;
typedef struct Api__AuthChallenge Api__AuthChallenge;
typedef struct Api__AuthResponse Api__AuthResponse;
typedef struct Api__AuthError Api__AuthError;
typedef struct Api__DeviceAuthMessage Api__DeviceAuthMessage;


/* --- enums --- */

/*
 * Always pass a version of the protocol for future compatibility
 * requirements.
 */
typedef enum _Api__CastMessage__ProtocolVersion {
  API__CAST_MESSAGE__PROTOCOL_VERSION__CASTV2_1_0 = 0
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(API__CAST_MESSAGE__PROTOCOL_VERSION)
} Api__CastMessage__ProtocolVersion;
/*
 * What type of data do we have in this message.
 */
typedef enum _Api__CastMessage__PayloadType {
  API__CAST_MESSAGE__PAYLOAD_TYPE__STRING = 0,
  API__CAST_MESSAGE__PAYLOAD_TYPE__BINARY = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(API__CAST_MESSAGE__PAYLOAD_TYPE)
} Api__CastMessage__PayloadType;
typedef enum _Api__AuthError__ErrorType {
  API__AUTH_ERROR__ERROR_TYPE__INTERNAL_ERROR = 0,
  /*
   * The underlying connection is not TLS
   */
  API__AUTH_ERROR__ERROR_TYPE__NO_TLS = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(API__AUTH_ERROR__ERROR_TYPE)
} Api__AuthError__ErrorType;

/* --- messages --- */

struct  Api__CastMessage
{
  ProtobufCMessage base;
  Api__CastMessage__ProtocolVersion protocol_version;
  /*
   * source and destination ids identify the origin and destination of the
   * message.  They are used to route messages between endpoints that share a
   * device-to-device channel.
   * For messages between applications:
   *   - The sender application id is a unique identifier generated on behalf of
   *     the sender application.
   *   - The receiver id is always the the session id for the application.
   * For messages to or from the sender or receiver platform, the special ids
   * 'sender-0' and 'receiver-0' can be used.
   * For messages intended for all endpoints using a given channel, the
   * wildcard destination_id '*' can be used.
   */
  char *source_id;
  char *destination_id;
  /*
   * This is the core multiplexing key.  All messages are sent on a namespace
   * and endpoints sharing a channel listen on one or more namespaces.  The
   * namespace defines the protocol and semantics of the message.
   */
  char *namespace_;
  Api__CastMessage__PayloadType payload_type;
  /*
   * Depending on payload_type, exactly one of the following optional fields
   * will always be set.
   */
  char *payload_utf8;
  protobuf_c_boolean has_payload_binary;
  ProtobufCBinaryData payload_binary;
};
#define API__CAST_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&api__cast_message__descriptor) \
    , API__CAST_MESSAGE__PROTOCOL_VERSION__CASTV2_1_0, NULL, NULL, NULL, API__CAST_MESSAGE__PAYLOAD_TYPE__STRING, NULL, 0, {0,NULL} }


/*
 * Messages for authentication protocol between a sender and a receiver.
 */
struct  Api__AuthChallenge
{
  ProtobufCMessage base;
};
#define API__AUTH_CHALLENGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&api__auth_challenge__descriptor) \
     }


struct  Api__AuthResponse
{
  ProtobufCMessage base;
  ProtobufCBinaryData signature;
  ProtobufCBinaryData client_auth_certificate;
};
#define API__AUTH_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&api__auth_response__descriptor) \
    , {0,NULL}, {0,NULL} }


struct  Api__AuthError
{
  ProtobufCMessage base;
  Api__AuthError__ErrorType error_type;
};
#define API__AUTH_ERROR__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&api__auth_error__descriptor) \
    , API__AUTH_ERROR__ERROR_TYPE__INTERNAL_ERROR }


struct  Api__DeviceAuthMessage
{
  ProtobufCMessage base;
  /*
   * Request fields
   */
  Api__AuthChallenge *challenge;
  /*
   * Response fields
   */
  Api__AuthResponse *response;
  Api__AuthError *error;
};
#define API__DEVICE_AUTH_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&api__device_auth_message__descriptor) \
    , NULL, NULL, NULL }


/* Api__CastMessage methods */
void   api__cast_message__init
                     (Api__CastMessage         *message);
size_t api__cast_message__get_packed_size
                     (const Api__CastMessage   *message);
size_t api__cast_message__pack
                     (const Api__CastMessage   *message,
                      uint8_t             *out);
size_t api__cast_message__pack_to_buffer
                     (const Api__CastMessage   *message,
                      ProtobufCBuffer     *buffer);
Api__CastMessage *
       api__cast_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   api__cast_message__free_unpacked
                     (Api__CastMessage *message,
                      ProtobufCAllocator *allocator);
/* Api__AuthChallenge methods */
void   api__auth_challenge__init
                     (Api__AuthChallenge         *message);
size_t api__auth_challenge__get_packed_size
                     (const Api__AuthChallenge   *message);
size_t api__auth_challenge__pack
                     (const Api__AuthChallenge   *message,
                      uint8_t             *out);
size_t api__auth_challenge__pack_to_buffer
                     (const Api__AuthChallenge   *message,
                      ProtobufCBuffer     *buffer);
Api__AuthChallenge *
       api__auth_challenge__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   api__auth_challenge__free_unpacked
                     (Api__AuthChallenge *message,
                      ProtobufCAllocator *allocator);
/* Api__AuthResponse methods */
void   api__auth_response__init
                     (Api__AuthResponse         *message);
size_t api__auth_response__get_packed_size
                     (const Api__AuthResponse   *message);
size_t api__auth_response__pack
                     (const Api__AuthResponse   *message,
                      uint8_t             *out);
size_t api__auth_response__pack_to_buffer
                     (const Api__AuthResponse   *message,
                      ProtobufCBuffer     *buffer);
Api__AuthResponse *
       api__auth_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   api__auth_response__free_unpacked
                     (Api__AuthResponse *message,
                      ProtobufCAllocator *allocator);
/* Api__AuthError methods */
void   api__auth_error__init
                     (Api__AuthError         *message);
size_t api__auth_error__get_packed_size
                     (const Api__AuthError   *message);
size_t api__auth_error__pack
                     (const Api__AuthError   *message,
                      uint8_t             *out);
size_t api__auth_error__pack_to_buffer
                     (const Api__AuthError   *message,
                      ProtobufCBuffer     *buffer);
Api__AuthError *
       api__auth_error__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   api__auth_error__free_unpacked
                     (Api__AuthError *message,
                      ProtobufCAllocator *allocator);
/* Api__DeviceAuthMessage methods */
void   api__device_auth_message__init
                     (Api__DeviceAuthMessage         *message);
size_t api__device_auth_message__get_packed_size
                     (const Api__DeviceAuthMessage   *message);
size_t api__device_auth_message__pack
                     (const Api__DeviceAuthMessage   *message,
                      uint8_t             *out);
size_t api__device_auth_message__pack_to_buffer
                     (const Api__DeviceAuthMessage   *message,
                      ProtobufCBuffer     *buffer);
Api__DeviceAuthMessage *
       api__device_auth_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   api__device_auth_message__free_unpacked
                     (Api__DeviceAuthMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Api__CastMessage_Closure)
                 (const Api__CastMessage *message,
                  void *closure_data);
typedef void (*Api__AuthChallenge_Closure)
                 (const Api__AuthChallenge *message,
                  void *closure_data);
typedef void (*Api__AuthResponse_Closure)
                 (const Api__AuthResponse *message,
                  void *closure_data);
typedef void (*Api__AuthError_Closure)
                 (const Api__AuthError *message,
                  void *closure_data);
typedef void (*Api__DeviceAuthMessage_Closure)
                 (const Api__DeviceAuthMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor api__cast_message__descriptor;
extern const ProtobufCEnumDescriptor    api__cast_message__protocol_version__descriptor;
extern const ProtobufCEnumDescriptor    api__cast_message__payload_type__descriptor;
extern const ProtobufCMessageDescriptor api__auth_challenge__descriptor;
extern const ProtobufCMessageDescriptor api__auth_response__descriptor;
extern const ProtobufCMessageDescriptor api__auth_error__descriptor;
extern const ProtobufCEnumDescriptor    api__auth_error__error_type__descriptor;
extern const ProtobufCMessageDescriptor api__device_auth_message__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_cast_5fchannel_2eproto__INCLUDED */
